### ISSUE TITLE
sphinx issues 投稿(Customizing a sphinx.ext.todo... )の返信の英文を作って投下する

### ISSUE THREAD

**Issue by shouh** [shouh/issueet#705]

**Comment by shouh** [comment]
`:+1: ` :+1:  これね。

**Comment by shouh** [comment]
元ネタは https://github.com/sphinx-doc/sphinx/issues/2730 これね

**Comment by shouh** [comment]
うお、url で言及したら向こう側にも飛ぶとかｗｗ  ちょっとタイトルをダサくない程度に書き直す。

**Comment by shouh** [comment]
個人的な TODO が向こう側に反映された形になっちゃったけど、いいのかなあ。……まあ叱られたら消すか。

**Comment by tk0miya** [comment]
お邪魔します！

参照が飛ぶのはあまり気にしなくて大丈夫ですよ。よくあることなので :-)
込み入った議論が必要そうなら、日本語でやり取りもできますよ。

**Comment by shouh** [comment]
コメントありがとうございます！
よくあるとのことなので、安心しました :sweat:
議論は不要そうです。せっかくご提示いただいたサンプルがあるので、活用させていただきます :smile:

**Comment by shouh** [comment]
close
